global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'leviathan'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["leviathan.home.lan:9100"]

  - job_name: 'SAI'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["leviathan.home.lan:9162"]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['leviathan.home.lan:8090']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['leviathan.home.lan:9090']

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']

  - job_name: 'valhalla'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.15:9100']

  - job_name: 'homeassistant'
    scrape_interval: 60s
    metrics_path: /api/prometheus
    bearer_token: secretToken
    static_configs:
      - targets: ["hass.leviathan.home.lan:8123"]

# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets: 
#       - 'alertmanager:9093'


remote_write:
- url: http://influxdb.leviathan.home.lan:8086/api/v1/prom/write?u=hass&p=hass&db=hass
  remote_timeout: 30s
  write_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (homeassistant_sensor_power_w)
    replacement: $1
    action: keep
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
  metadata_config:
    send: true
    send_interval: 1m
remote_read:
- url: http://influxdb.leviathan.home.lan:8086/api/v1/prom/read?u=hass&p=hass&db=hass
  remote_timeout: 1m

