global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'leviathan'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: 'SAI'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["localhost:9162"]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']

  - job_name: 'pantalones'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.0.18:9100']

  - job_name: 'valhalla'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.0.15:9100']

  - job_name: 'homeassistant'
    scrape_interval: 60s
    metrics_path: /api/prometheus
    bearer_token: s 
    static_configs:
      - targets: ["localhost:8123"]

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']

# Remote write configuration InfluxDB
remote_write:
- url: "http://localhost:8086/api/v1/prom/write?u=prometheus&p=prometheus&db=home_assistant"
# Remote read configuration for InfluxDB
remote_read:
- url: "http://localhost:8086/api/v1/prom/read?u=prometheus&p=prometheus&db=home_assistant"
